name: pycytominer-example
channels:
- conda-forge
dependencies:
- conda-forge::python
- conda-forge::pandas
- conda-forge::numpy
- conda-forge::pathlib
- conda-forge::requests
- conda-forge::jupyter
- conda-forge::jupyterlab
- conda-forge::ipykernel
- conda-forge::nb_conda_kernels
- conda-forge::widgetsnbextension
- conda-forge::jupyter_contrib_nbextensions
- conda-forge::matplotlib
- conda-forge::plotnine
- conda-forge::seaborn
- conda-forge::black
- pip:
  - git+https://github.com/cytomining/pycytominer@8e3c28d3b81efd2c241d4c792edfefaa46698115
  - git+https://github.com/cytomining/cytominer-eval@643d3e7fc97464a1b45a4642fa921cc22269b118
